### ISSUE TITLE
auto-brain-reconstruction and Shading Artifact

### ISSUE THREAD

**Issue by jfpva** [SVRTK/auto-proc-svrtk#2]
The auto-brain-reconstruction script generally works very well with our 3T fetal brain SSFSE data, however, I've run into a few cases with (modest?) shading artifact where the masks generated in auto-brain-reconstruction seem to be slightly off such that the SVR volume doesn't fully cover the brain. 

The image below shows two examples of the problem, where the acquired images have some shading (similar shading in all orientations) along with the resulting auto-brain-recon volume image at the same location, showing the ROI used in SVR doesn't cover the entire brain. 

Looking at the intermediate files, it appears this issue results from inaccuracies of the brain localisation segmentation step in areas where the signal is lower. 

Is there a suggested approach to successfully run auto-brain-reconstruction for images with some shading artifact? Some preliminary tests suggest that applying bias correction to the acquired images and/or performing SVR with manual template and mask selection may overcome the issue in some cases. However, a robust fully automated pipeline would clearly be the ideal. 

Thanks in advance for any guidance!

![fetal_brain_ssfse_shading](https://github.com/SVRTK/auto-proc-svrtk/assets/4388495/7e474658-4085-41dd-be51-ecbeb51ebbd0)

**Comment by alenauus** [comment]
should have been partially fixed in the recent update

**Comment by jfpva** [comment]
Applying bias correction to the acquired images alone didn't overcome this issue, but this latest update (sha:
[eb04bbc](https://github.com/SVRTK/auto-proc-svrtk/commit/eb04bbceed95607a876ce76abff80f5c341ad2f3)) seems to work in all the cases we've tested so far where we'd expect it to.

![fetal_brain_ssfse_shading_fix](https://github.com/SVRTK/auto-proc-svrtk/assets/4388495/c670af76-e819-4e5a-870f-28515c8b6aed)

Thanks!
